{% set name = "google-cloud-core" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-core-{{ version }}.tar.gz
  sha256: 37b80273c8d7eee1ae816b3a20ae43585ea50506cb0e60f3cf5be5f87f1373cb

build:
  number: 0
  noarch: python
  script: pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools

  run:
    - python >=3.7
    - google-api-core >=1.31.6,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0dev
    # grpc extra
    - grpcio >=1.38.0,<2.0.0dev

test:
  requires:
    - pip
  imports:
    - google.api_core.client_info
    - google.cloud.client
    - google.cloud.environment_vars
    - google.cloud.exceptions
    - google.cloud.operation
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-cloud-core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'API Client library for Google Cloud: Core Helpers'
  description: This library is not meant to stand-alone. Instead it defines common helpers (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://googleapis.dev/python/google-cloud-core/latest/
  dev_url: https://github.com/googleapis/python-cloud-core

extra:
  recipe-maintainers:
    - xylar
    - leahecole
    - parthea
    - tswast
